name: CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Download dependencies
        run: sudo apt-get -y install build-essential clang bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev

      - name: git clone submodules
        run: git submodule update --init

      - name: build
        run: make

      - name: tests
        run: make tests
